### ISSUE TITLE
Make the logging option a command line argument

### ISSUE THREAD

**Issue by Hungry-Dolphin** [Hungry-Dolphin/NyaaSort#3]
Right now the script will ask you if you want logging enabled or not, It would be nice if you could give it a flag or an option so the script knows if you want to enable it or not, 

This makes it cleaner to run the application from the command line, and helps with integration testing aswell since you won't have to tell it you want to enable logging every time

**Comment by Piyush-Kumar-Behera** [comment]
Can you please tell the default value of logging if no argument is passed, or should in that case the user will be prompted to enter the logging value?

**Comment by Hungry-Dolphin** [comment]
On default the user will be asked if they want to enable it yes or no(as shown in the code snippet below). 
![image](https://user-images.githubusercontent.com/31831543/102121297-0c4cf380-3e44-11eb-8003-197fe463ad9d.png)

This interaction is fine for windows since you will most likely run the script by double clicking it. 
But if you want to set up this program using the command line or some other script this can cause some issues. 

You could remove this issue in a few ways. One example would be by making it accept a flag like --logging=True were the program will look for this flag and only ask the user if it want to enable logging when no flag was provided.

However feel free to come up with a way to solve this issue in a way you think would be best. 
The main issue is that needs to be adjusted is that you need to be able to set up the script without providing further input. Because that would make automating the setup process way simpler, and would also make integration testing simpler since you wont have fill in the logging option each time.
